@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package weightedgpa.infinibiome.internal.floatfunc.generators;


import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;