@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package weightedgpa.infinibiome.internal.misc;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;