@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package weightedgpa.infinibiome.internal.generators.nonworldgen;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;