@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package weightedgpa.infinibiome.internal.floatfunc.modifiers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;