@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package weightedgpa.infinibiome.internal.generators.interchunks.struct;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;